/**
 * Stamps a content hash of public/assets into src/asset-version.js.
 *
 *   node tools/asset-version.mjs
 *
 * Run after any asset generator. Every generated texture and model lives in
 * `public/`, which Vite copies verbatim — no content hash in the filename, and
 * therefore no way for a browser to know the bytes behind `/assets/textures/
 * gunmetal_orm.webp` ever changed. A player with a warm cache keeps the old asset
 * indefinitely.
 *
 * That is not a theoretical problem. A roughness map that baked to zero shipped a
 * mirror-finish weapon; the fix landed, and the report came back unchanged, because
 * the browser never re-fetched the file. Two rounds went into re-diagnosing a bug
 * that was already fixed.
 *
 * The hash goes into a source module rather than a JSON file the game fetches:
 * Vite hashes the JS bundle itself, so the constant is always fresh with no extra
 * round-trip and nothing to get stale on its own.
 */
import { createHash } from 'node:crypto';
import { readdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const ASSETS = resolve(ROOT, 'public/assets');
const OUT = resolve(ROOT, 'src/asset-version.js');

async function* walk(dir) {
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const p = resolve(dir, entry.name);
    if (entry.isDirectory()) yield* walk(p);
    else yield p;
  }
}

const files = [];
for await (const f of walk(ASSETS)) files.push(f);
// Sorted, so the hash depends on the bytes and not on directory order.
files.sort();

const h = createHash('sha256');
for (const f of files) {
  h.update(relative(ASSETS, f).replace(/\\/g, '/'));
  h.update(await readFile(f));
}
const version = h.digest('hex').slice(0, 12);

await writeFile(OUT, `// Generated by tools/asset-version.mjs — do not edit.
//
// A content hash of everything under public/assets. Appended to every asset URL so a
// regenerated texture or model actually reaches a browser that already cached the old
// one; see that script for why this is not optional.
export const ASSET_VERSION = '${version}';

/** Append the cache-busting stamp to an asset URL. */
export function versioned(url) {
  return \`\${url}?v=\${ASSET_VERSION}\`;
}
`);
console.log(`asset-version  ${files.length} files  ${version}`);
