// Generated by tools/asset-version.mjs — do not edit.
//
// A content hash of everything under public/assets. Appended to every asset URL so a
// regenerated texture or model actually reaches a browser that already cached the old
// one; see that script for why this is not optional.
export const ASSET_VERSION = '0c5c8fb646fc';

/** Append the cache-busting stamp to an asset URL. */
export function versioned(url) {
  return `${url}?v=${ASSET_VERSION}`;
}
